# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claustro < Formula
  desc "Disposable Docker sandboxes for Claude Code"
  homepage "https://github.com/uniforgeai/claustro"
  version "0.6.0"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.6.0/claustro_0.6.0_darwin_amd64.zip"
      sha256 "e9c8c0809eee993e83e05271f6b20da3015b498299eb0f162ac791c66e091b01"

      define_method(:install) do
        bin.install "claustro"
        bin.install "claustrod"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.6.0/claustro_0.6.0_darwin_arm64.zip"
      sha256 "c3038feb4161d40a07bc6f99e9ff13c403268abe9405d7b494da13dc0861275f"

      define_method(:install) do
        bin.install "claustro"
        bin.install "claustrod"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.6.0/claustro_0.6.0_linux_amd64.tar.gz"
      sha256 "a91043480e5943dd4d2b0d0c5592662e51dde9b0b5c0ec2054195d9d72f67f03"
      define_method(:install) do
        bin.install "claustro"
        bin.install "claustrod"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.6.0/claustro_0.6.0_linux_arm64.tar.gz"
      sha256 "8361f8847de2559fe7e2ef26d2d4369143448860e67eb6173d0f62467426e61b"
      define_method(:install) do
        bin.install "claustro"
        bin.install "claustrod"
      end
    end
  end

  test do
    system "#{bin}/claustro", "--help"
  end
end
