# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claustro < Formula
  desc "Disposable Docker sandboxes for Claude Code"
  homepage "https://github.com/uniforgeai/claustro"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.1.0/claustro_0.1.0_darwin_amd64.zip"
      sha256 "e4da2fa18ce9329a70d29b95cbfa9ee39254ec3cd64c7db31272f776ba1424d2"

      define_method(:install) do
        bin.install "claustro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.1.0/claustro_0.1.0_darwin_arm64.zip"
      sha256 "7729e4045d29851f772b56030cfd545e954fc27b6dd5df13efd50e397be4e72b"

      define_method(:install) do
        bin.install "claustro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.1.0/claustro_0.1.0_linux_amd64.tar.gz"
      sha256 "b396dc007df38ef3c20a9cb715a78663e9ca3e2f869024fa76ff16b08718a3ff"
      define_method(:install) do
        bin.install "claustro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.1.0/claustro_0.1.0_linux_arm64.tar.gz"
      sha256 "f0465be68611779efca346f72eb4acea5dac95f0c2825936ce7f7f18f3a1bf07"
      define_method(:install) do
        bin.install "claustro"
      end
    end
  end

  test do
    system "#{bin}/claustro", "--help"
  end
end
