# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_github_release_download_strategy"
class Claustro < Formula
  desc "Disposable Docker sandboxes for Claude Code"
  homepage "https://github.com/uniforgeai/claustro"
  version "0.7.0"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.7.0/claustro_0.7.0_darwin_amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9791c6e1b6de3854cc0378d54389d2ca6c6aef932ecbc79edd33db67a07a6e8d"

      define_method(:install) do
        bin.install "claustro"
        bin.install "claustrod"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.7.0/claustro_0.7.0_darwin_arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "524d74ee7dd1c339b4180d625bd78125ba29ba457c93702563b42315473abdf4"

      define_method(:install) do
        bin.install "claustro"
        bin.install "claustrod"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.7.0/claustro_0.7.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ae381159935d920d0e199a49b3e51ac9b9a1912f2860a9dec477063bb5763795"
      define_method(:install) do
        bin.install "claustro"
        bin.install "claustrod"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uniforgeai/claustro/releases/download/v0.7.0/claustro_0.7.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3580c109c063d177f7c6de233ac1ad580685aa14fedf3beaa304ad60a3eccf03"
      define_method(:install) do
        bin.install "claustro"
        bin.install "claustrod"
      end
    end
  end

  test do
    system "#{bin}/claustro", "--help"
  end
end
