# This file was generated by GoReleaser. DO NOT EDIT.
cask "claustro" do
  require_relative "../lib/private_github_release_download_strategy"

  # Homebrew no longer accepts --no-quarantine. Drop Gatekeeper's
  # attribute from this cask's staged directory only.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path.to_s],
                   must_succeed: false
  end

  version "0.13.9"

  on_macos do
    on_arm do
      sha256 "be7cd617f1d2c8b8d1faef0aefbb58c59204cf1b8be8ffdaabef484fc2ee577b"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_darwin_arm64.zip",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "e26c2098cc36944ba749ac84ca1d4d7760792a23b49c8c78c7a12b3d03255c2e"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_darwin_amd64.zip",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end
  on_linux do
    on_arm do
      sha256 "9b14d355629e2882969655c2059222df4616fc756aa470328d41bfb8d085ddeb"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_linux_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "c67fd0b9ad279744f60707998db4e27d07cd0de1b36bed5425ae39ab784a8683"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_linux_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "claustro"
  desc "Disposable Docker sandboxes for Claude Code"
  homepage "https://github.com/uniforgeai/claustro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claustro"
  binary "claustrod"

  # No zap stanza required
end
