# This file was generated by GoReleaser. DO NOT EDIT.
cask "claustro" do
  require_relative "../lib/private_github_release_download_strategy"

  version "0.13.3"

  on_macos do
    on_arm do
      sha256 "3752edafafc260ff3417064196ba827751e2d5d143202481a1d895a189827620"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_darwin_arm64.zip",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "81420ca48f0db1349ff5e286d9adb51220bf15f0d609925c3b9c71601a0ad6e5"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_darwin_amd64.zip",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end
  on_linux do
    on_arm do
      sha256 "30cc9273ab00b977839612d3a71d13a92ebb406e9e3c328e0a82147c59a51e72"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_linux_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "7046ed145d9da09905234f2d37b7ce2255c7aa15b67c9a65eb2121951f997e37"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_linux_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "claustro"
  desc "Disposable Docker sandboxes for Claude Code"
  homepage "https://github.com/uniforgeai/claustro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claustro"
  binary "claustrod"

  # No zap stanza required
end
