# This file was generated by GoReleaser. DO NOT EDIT.
cask "claustro" do
  require_relative "../lib/private_github_release_download_strategy"

  version "0.13.2"

  on_macos do
    on_arm do
      sha256 "946707201eccd4e089eb483a9ef3d141c055f919354eb76703b838191cb7369f"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_darwin_arm64.zip",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "bbff6aedd02a77c89ec4027f4a7dca265f74cb27a9b8d55e37b9f490730e91c2"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_darwin_amd64.zip",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end
  on_linux do
    on_arm do
      sha256 "9de48323f2938add99700d7bb340b4f936bcb2190e5000d64811508559cbb452"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_linux_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "18c14e9d7fcc9c03999e6ee3bc9b128a61bc7204629eabc29b45904817913848"
      url "https://github.com/uniforgeai/claustro/releases/download/v#{version}/claustro_#{version}_linux_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "claustro"
  desc "Disposable Docker sandboxes for Claude Code"
  homepage "https://github.com/uniforgeai/claustro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claustro"
  binary "claustrod"

  # No zap stanza required
end
